/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.sun.corba.se.spi.orbutil.threadpool.ThreadPool;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingWorker;
import servidortre.ServidorTRE;

/**
 *
 * @author charles
 */
public class FrameTRE extends javax.swing.JFrame {

    /**
     * Creates new form FrameTRE
     */
    
    //int gvn1=0,gvn2=0,gvnB=0,gvnN=0,psd1=0,psd2=0,psdB=0,psdN=0;
    private static int[] votosValor = {0,0,0,0,0,0,0,0}; 
    public ServidorTRE servidorTRE;
    public FrameTRE(ServidorTRE servidorTRE) {
        initComponents();
        this.servidorTRE = servidorTRE;
        jLabel3.setVisible(false);
    }
    public FrameTRE(){}
    
    
    
    String total = "";
    public void calcularVotos(String votos){
        System.out.println(votos);
        String[] array = votos.split(" ");
          
            votosValor[0] += Integer.parseInt(array[0]);
            votosValor[1] += Integer.parseInt(array[1]);
            votosValor[2] += Integer.parseInt(array[2]);
            votosValor[3] += Integer.parseInt(array[3]);
            votosValor[4] += Integer.parseInt(array[4]);
            votosValor[5] += Integer.parseInt(array[5]);
            votosValor[6] += Integer.parseInt(array[6]);
            votosValor[7] += Integer.parseInt(array[7]);
            
            gvn1.setText(String.valueOf(votosValor[0]));
            gvn2.setText(String.valueOf(votosValor[1]));
            gvnBranco.setText(String.valueOf(votosValor[2]));
            gvnNulo.setText(String.valueOf(votosValor[3]));
            
            psd1.setText(String.valueOf(votosValor[4]));
            psd2.setText(String.valueOf(votosValor[5]));
            psdBranco.setText(String.valueOf(votosValor[6]));
            psdNulo.setText(String.valueOf(votosValor[7]));
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        g5 = new javax.swing.JLabel();
        gvn1 = new javax.swing.JTextField();
        g6 = new javax.swing.JLabel();
        gvn2 = new javax.swing.JTextField();
        g7 = new javax.swing.JLabel();
        gvnBranco = new javax.swing.JTextField();
        g8 = new javax.swing.JLabel();
        gvnNulo = new javax.swing.JTextField();
        g9 = new javax.swing.JLabel();
        psd1 = new javax.swing.JTextField();
        g10 = new javax.swing.JLabel();
        psd2 = new javax.swing.JTextField();
        g11 = new javax.swing.JLabel();
        psdBranco = new javax.swing.JTextField();
        g12 = new javax.swing.JLabel();
        psdNulo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tsePorta = new javax.swing.JTextField();
        tseIP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setText("TRE - São Paulo");
        jLabel1.setAlignmentY(0.0F);

        jLabel2.setText("Porta:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Ligar Servidor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Enviar Resultado");
        jButton2.setActionCommand("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(43, 183, 60));
        jLabel3.setText("Cliente Conectado");
        jLabel3.setAlignmentY(0.0F);

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(58, 58, 58));
        jLabel5.setText("Resultado");
        jLabel5.setAlignmentY(0.0F);

        g5.setText("Governador1:");
        g5.setName(""); // NOI18N

        gvn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gvn1ActionPerformed(evt);
            }
        });

        g6.setText("Governador2:");
        g6.setName(""); // NOI18N

        gvn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gvn2ActionPerformed(evt);
            }
        });

        g7.setText("Governador Branco:");
        g7.setName(""); // NOI18N

        gvnBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gvnBrancoActionPerformed(evt);
            }
        });

        g8.setText("Governador Nulo:");
        g8.setName(""); // NOI18N

        gvnNulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gvnNuloActionPerformed(evt);
            }
        });

        g9.setText("Presidente1:");
        g9.setName(""); // NOI18N

        psd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psd1ActionPerformed(evt);
            }
        });

        g10.setText("Presidente2:");
        g10.setName(""); // NOI18N

        psd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psd2ActionPerformed(evt);
            }
        });

        g11.setText("Presidente Branco:");
        g11.setName(""); // NOI18N

        psdBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psdBrancoActionPerformed(evt);
            }
        });

        g12.setText("Presidente Nulo:");
        g12.setName(""); // NOI18N

        psdNulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psdNuloActionPerformed(evt);
            }
        });

        jLabel6.setText("Porta:");

        tsePorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsePortaActionPerformed(evt);
            }
        });

        tseIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tseIPActionPerformed(evt);
            }
        });

        jLabel7.setText("IP:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(g7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(g6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(7, 7, 7)
                                    .addComponent(gvn2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(g8))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gvnNulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gvnBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(221, 221, 221))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(psdNulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(g5)
                                        .addGap(33, 33, 33)
                                        .addComponent(gvn1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tsePorta, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(g10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(g9))
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(psd1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(psd2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(g11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(psdBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(g12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tseIP, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 46, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jButton1)))))
                        .addGap(295, 295, 295))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g5)
                    .addComponent(g9)
                    .addComponent(psd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gvn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(g10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(g6)
                        .addComponent(gvn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(psd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g7)
                    .addComponent(gvnBranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g11)
                    .addComponent(psdBranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(g8)
                    .addComponent(gvnNulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g12)
                    .addComponent(psdNulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tseIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tsePorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            int porta = Integer.parseInt(jTextField1.getText());
            
            SwingWorker swingWorker = new SwingWorker() {
                @Override
                protected Object doInBackground() throws Exception {
                    servidorTRE.configurarServidor(porta);
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                    
                }
            };
            swingWorker.execute();
            /*ServerSocket serverSocket = new ServerSocket(porta);
            Socket socket = serverSocket.accept();
            jLabel3.setVisible(true);
            
            BufferedReader reader =  new BufferedReader(new InputStreamReader(socket.getInputStream()));
            String votos = reader.readLine();
            String[] array = votos.split(" ");
            
            vg1 += Integer.parseInt(array[0]);
            vg2 += Integer.parseInt(array[1]);
            vg3 += Integer.parseInt(array[2]);
            vg4 += Integer.parseInt(array[3]);
            vp1 += Integer.parseInt(array[4]);
            vp2 += Integer.parseInt(array[5]);
            vp3 += Integer.parseInt(array[6]);
            vp1 += Integer.parseInt(array[7]);
            
            g1.setText(String.valueOf(vg1));
            g2.setText(String.valueOf(vg2));
            g3.setText(String.valueOf(vg3));
            g4.setText(String.valueOf(vg4));
            
            p1.setText(String.valueOf(vp1));
            p2.setText(String.valueOf(vp2));
            p3.setText(String.valueOf(vp3));
            p4.setText(String.valueOf(vp4));*/
            

        } catch (Exception e) {
            Logger.getLogger(FrameTRE.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String ip = tseIP.getText();
        int porta = Integer.parseInt(tsePorta.getText());
        
        total = "";
        total +=String.valueOf(votosValor[0])+" ";
        total +=String.valueOf(votosValor[1])+" ";
        total +=String.valueOf(votosValor[2])+" ";
        total +=String.valueOf(votosValor[3])+" ";
        total +=String.valueOf(votosValor[4])+" ";
        total +=String.valueOf(votosValor[5])+" ";
        total +=String.valueOf(votosValor[6])+" ";
        total +=String.valueOf(votosValor[7])+" ";
        servidorTRE.enviarDados(total, ip, porta);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void gvn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gvn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gvn1ActionPerformed

    private void gvn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gvn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gvn2ActionPerformed

    private void gvnBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gvnBrancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gvnBrancoActionPerformed

    private void gvnNuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gvnNuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gvnNuloActionPerformed

    private void psd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psd1ActionPerformed

    private void psd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psd2ActionPerformed

    private void psdBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psdBrancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psdBrancoActionPerformed

    private void psdNuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psdNuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psdNuloActionPerformed

    private void tsePortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsePortaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsePortaActionPerformed

    private void tseIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tseIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tseIPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTRE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTRE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTRE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTRE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTRE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel g10;
    private javax.swing.JLabel g11;
    private javax.swing.JLabel g12;
    private javax.swing.JLabel g5;
    private javax.swing.JLabel g6;
    private javax.swing.JLabel g7;
    private javax.swing.JLabel g8;
    private javax.swing.JLabel g9;
    private javax.swing.JTextField gvn1;
    private javax.swing.JTextField gvn2;
    private javax.swing.JTextField gvnBranco;
    private javax.swing.JTextField gvnNulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField psd1;
    private javax.swing.JTextField psd2;
    private javax.swing.JTextField psdBranco;
    private javax.swing.JTextField psdNulo;
    private javax.swing.JTextField tseIP;
    private javax.swing.JTextField tsePorta;
    // End of variables declaration//GEN-END:variables
}
